baseURL = "https://akarru.com/"
languageCode = "es"
title = "Akarrú"
theme = "ananke"
paginate = 10
disqusShortname = "akarru"
googleAnalytics = ""

MetaDataFormat = "yaml"
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
enableEmoji = true
fencedCode = true

[permalinks]
    post = "/blog/:year/:month/:day/:slug"
    

[params]
  favicon = ""
  description = "El tiempo ha llegado, dijo la morsa, de hablar de muchas cosas."
  facebook = ""
  twitter = "https://twitter.com/lnds"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/banner.jpg"
  recent_posts_number = 10
  show_reading_time = true

